\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{reportTemplateOxford}[2025/03/11 template for Oxford 3YP and 4YP]

\LoadClass[11pt]{article}

% GUIDELINES
% - Submit by noon on Wednesday of the fourth week of Trinity Term
% - Plagiarism! The University regards plagiarism in examinations as a serious matter. Cases will be investigated and penalties may range from deduction of marks to expulsion from the University, depending on the seriousness of the occurrence. Even if plagiarism is inadvertent, it can result in a penalty.
% - 30 pages per student
% - 20 mm margins
% - Arial (or similar) font size 11
% - Double line spacing

\usepackage[margin=20 mm]{geometry}
\usepackage{fontspec}
\usepackage{setspace}
\doublespacing
\setmainfont{Arial}

\usepackage{lipsum}

\usepackage{graphicx}
\usepackage{subcaption}
\usepackage{duckuments}

\usepackage{booktabs}

\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhead[L]{} % Left side of the header
\fancyhead[C]{} % Center of the header (optional)
\fancyhead[R]{} % Right side of the header (optional)

\usepackage{glossaries}
\makeglossaries

\newcommand{\subtitle}[1]{\def\@subtitle{#1}} 

\renewcommand{\maketitle}{
\begin{titlepage}
    \centering
    \vspace*{1cm}

    \includegraphics[width=0.4\textwidth]{figs/OxEng Logo.pdf}

    \vspace*{1cm}

    \Huge
    \textbf{\@title}

    \vspace{0.5cm}
    \LARGE
    \@subtitle

    \vfill

    \vspace{1.5cm}

    \textbf{\@author}

    \Large
    \@date

    \thispagestyle{empty} % Suppress page number on the title page
\end{titlepage}
}

\usepackage{setspace}
\usepackage{multicol}

\newcommand{\printbibliography}[2]{
\begingroup\onehalfspacing
{\small
\begin{multicols}{2}
\bibliographystyle{plain}
\bibliography{#1}
\end{multicols}}
\endgroup
}

% ADD ACRONYMS HERE
\newacronym{3yp}{3YP}{Third-Year Project}
\newacronym{cpp}{CPP}{Coverage Path Planning}
\newacronym{tsp}{TSP}{Travelling Salesman Problem}
\newacronym{tspo}{TSP-O}{Travelling Salesman Problem with Obstacles}
\newacronym{roi}{ROI}{Region of Interest}
\newacronym{gis}{GIS}{Geographic Information System}
\newacronym{qgis}{QGIS}{Quantum Geographic Information System}
\newacronym{cgal}{CGAL}{Computational Geometry Algorithms Library}
\newacronym{gpr}{GPR}{Ground Penetrating Radar}
\newacronym{gpsar}{GPSAR}{Ground Penetrating Synthetic Aperture Radar}
\newacronym{anfis}{ANFIS}{Adaptive Neuro Fuzzy Inference System}
\newacronym{lwir}{LWIR}{Long Wavelength Infrared}
\newacronym{cnn}{CNN}{Convolutional Neural Network}

%%% SAM ACRONYMS
\newacronym{lipo}{LiPo}{lithium polymer}
\newacronym{liion}{Li-ion}{lithium-ion}
\newacronym{gbp}{GBP}{Great British Pound}
\newacronym{resc}{ReSC}{resonant switched capacitor}
\newacronym{6s}{6s}{6-cell series}
\newacronym{6s3p}{6s3p}{6-series 3-parallel}
\newacronym{tim}{TIMs}{thermal interface materials}
\newacronym{dcdc}{DC-DC}{Direct Current to Direct Current [power converter]
}

\newacronym{bs}{BS}{British Standards}
\newacronym{esr}{ESR}{equivalent series resistance}
\newacronym{i2c}{I\textsuperscript{2}C}{Inter-Integrated Circuit }
\newacronym{uart}{UART}{Universal Asynchronous Receiver/Transmitter }
\newacronym{sram}{SRAM}{static random-access memory}
\newacronym{soc}{SOC}{state of charge}
\newacronym{ntc}{NTC}{negative-temperature-coefficient}
\newacronym{ekf}{EKF}{extended Kalman filter}
\newacronym{fem}{FEM}{finite element method}
\newacronym{mosfet}{MOSFET}{metal–oxide–semiconductor field-effect transistor}
\newacronym{cad}{CAD}{computer-aided design}
\newacronym{pid}{PID}{proportional–integral–derivative}
\newacronym{dnn}{DNN}{Deep Neural Network}
\newacronym{lqr}{LQR}{linear-quadratic regulator}
\newacronym{mpc}{MPC}{model predictive control}
\newacronym{pd}{PD}{proportional–derivative}
\newacronym{uav}{UAV}{Unmanned Aerial Vehicle}
\newacronym{bms}{BMS}{Battery Management System}
%%%

% ADD ADDITIONAL PACKAGES HERE
\usepackage{algpseudocode}
\usepackage{algorithm}
\usepackage{hyperref}

%STUFF SAM NEEDS

%%%
\usepackage{fontspec}
\usepackage{graphicx}
\usepackage{parskip}
\usepackage{multicol}
\usepackage{titlesec}
\usepackage{setspace}
\usepackage{amsmath}
\usepackage{nicematrix}
\usepackage[margin=20 mm]{geometry}
\usepackage{fancyhdr}
\usepackage{amsmath, amssymb, amsfonts, mathtools}
\usepackage{algorithm, algorithmic}
\usepackage{hyperref}
\usepackage{float}
\usepackage{subcaption}
\usepackage{array}
\usepackage{url}
\usepackage{wrapfig}
\usepackage{sidecap}
\usepackage{makecell}
\usepackage{booktabs}
\usepackage{import}

\usepackage{tikz}

\usepackage[table]{xcolor}
\definecolor{swotS}{RGB}{226,237,143}
\definecolor{swotW}{RGB}{247,193,139}
\definecolor{swotO}{RGB}{173,208,187}
\definecolor{swotT}{RGB}{192,165,184}
\usepackage[raster]{tcolorbox}

\usepackage{siunitx}



\usepackage{hyperref}

\usepackage{chngcntr}

\usepackage{titlesec}


%%%%%%%%%%%%%%%%%%%%%%%